//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: graduationWork.proto
namespace graduationWork
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"g_CreateCharaterInfo")]
  public partial class g_CreateCharaterInfo : global::ProtoBuf.IExtensible
  {
    public g_CreateCharaterInfo() {}
    
    private int _servant;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"servant", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int servant
    {
      get { return _servant; }
      set { _servant = value; }
    }
    private int _pkNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pkNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pkNum
    {
      get { return _pkNum; }
      set { _pkNum = value; }
    }
    private int _team;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"team", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int team
    {
      get { return _team; }
      set { _team = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"g_ReadySet")]
  public partial class g_ReadySet : global::ProtoBuf.IExtensible
  {
    public g_ReadySet()
        {
            player1 = new g_CreateCharaterInfo();
            player2 = new g_CreateCharaterInfo();
            player3 = new g_CreateCharaterInfo();
            player4 = new g_CreateCharaterInfo();
        }
    
    private graduationWork.g_CreateCharaterInfo _player1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public graduationWork.g_CreateCharaterInfo player1
    {
      get { return _player1; }
      set { _player1 = value; }
    }
    private graduationWork.g_CreateCharaterInfo _player2;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"player2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public graduationWork.g_CreateCharaterInfo player2
    {
      get { return _player2; }
      set { _player2 = value; }
    }
    private graduationWork.g_CreateCharaterInfo _player3;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"player3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public graduationWork.g_CreateCharaterInfo player3
    {
      get { return _player3; }
      set { _player3 = value; }
    }
    private graduationWork.g_CreateCharaterInfo _player4;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"player4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public graduationWork.g_CreateCharaterInfo player4
    {
      get { return _player4; }
      set { _player4 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"g_Vector3")]
  public partial class g_Vector3 : global::ProtoBuf.IExtensible
  {
    public g_Vector3() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"g_Transform")]
  public partial class g_Transform : global::ProtoBuf.IExtensible
  {
    public g_Transform()
        {
            _position = new g_Vector3();
            _rotation = new g_Vector3();
            _scale = new g_Vector3();
        }
    
    private int _packetNum;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"packetNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int packetNum
    {
      get { return _packetNum; }
      set { _packetNum = value; }
    }
    private graduationWork.g_Vector3 _position;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public graduationWork.g_Vector3 position
    {
      get { return _position; }
      set { _position = value; }
    }
    private graduationWork.g_Vector3 _rotation;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public graduationWork.g_Vector3 rotation
    {
      get { return _rotation; }
      set { _rotation = value; }
    }
    private graduationWork.g_Vector3 _scale;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"scale", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public graduationWork.g_Vector3 scale
    {
      get { return _scale; }
      set { _scale = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"g_Message")]
  public partial class g_Message : global::ProtoBuf.IExtensible
  {
    public g_Message() {}
    
    private string _message;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"g_DataSize")]
  public partial class g_DataSize : global::ProtoBuf.IExtensible
  {
    public g_DataSize() {}
    
    private int _clientNum;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"clientNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int clientNum
    {
      get { return _clientNum; }
      set { _clientNum = value; }
    }
    private graduationWork.g_DataType _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public graduationWork.g_DataType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _size;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"size", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int size
    {
      get { return _size; }
      set { _size = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"g_DataType")]
    public enum g_DataType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NULLDATA", Value=0)]
      NULLDATA = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROTOCOL", Value=1)]
      PROTOCOL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMMAND", Value=2)]
      COMMAND = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MESSAGE", Value=3)]
      MESSAGE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRANSFORM", Value=4)]
      TRANSFORM = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"READYSET", Value=5)]
      READYSET = 5
    }
  
}